name: gogs-ligf
  version: '0.11.91'
  summary: git server
  description: |
    This is my-snap's description. 
  grade: stable
  confinement: strict
  base: core18

  parts:
    gogs-ligf:
      # See 'snapcraft plugins'
      plugin: go
      go-importpath: github.com/ligf/gogs
      source: github.com/ligf/gogs.git
      source-tag: 'v0.11.91'
      source-type: git
      build-packages:
      - gcc
  apps:
    gogs-ligf:
      command: bin/gogs web
      plugs:
      - home
      - network
      - network-bind
      daemon: simple
