  name: gogs-ligf
  version: '0.11.91'
  summary: git server
  description: |
    This is my-snap's description. 
  grade: stable
  confinement: strict
  base: core20

  parts:
    gogs-ligf:
      # See 'snapcraft plugins'
      plugin: go
      # go-buildtags: 'v0.11.91'
      source-type: git
  apps:
    gogs-ligf:
      command: bin/gogs web
      plugs:
      - home
      - network
      - network-bind
      daemon: simple
